[greeter]
background=/usr/share/backgrounds/ilinux/default.png
theme-name=WhiteSur-Light
icon-theme-name=WhiteSur
cursor-theme-name=WhiteSur-cursors
cursor-theme-size=24
font-name=Inter 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~power
clock-format=%a %b %d  %l:%M %p
position=50%,center 50%,center
panel-position=top
user-background=false
